# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

plugins:
  - jekyll-feed

# Permalinks
permalink:        pretty

# Setup
title:            '@JohnKoepi'
tagline:          'on software engineering'
description:      'Made by <a href="https://twitter.com/JohnKoepi" target="_blank">@JohnKoepi</a>.'
url:              http://sitano.github.io
baseurl:          '/'

author:
  name:           'Ivan'
  url:            https://twitter.com/JohnKoepi

analytics:
  provider: google
  google:
    tracking_id: 'UA-53659396-1'

comments:
  provider: disqus
  disqus:
    short_name: 'sitanogithubio'

# Custom vars
version:          v1.1.0

github:
  repo:           https://github.com/sitano/sitano.github.io

graphviz:
  options: "-Tsvg" # 'dot' command option
  command: "dot"   # execute this string. specify full path to 'dot' if you need
